var calendarList = {
    "calendars":[{
        "id":1,
        "title":"Home",
        "color":2
    },{
        "id":2,
        "title":"Work",
        "color":19
    },{
        "id":3,
        "title":"School",
        "color":6
    },{
        "id":4,
        "title":"Sports",
        "hidden":true,
        "color":27
    }]
};
